services:
  database:
    image: arm64v8/mariadb:11.3.2
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--protocol=tcp", "-u$$MARIADB_USER", "-p$$MARIADB_PASSWORD" ]
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - backend

  redis:
    image: arm64v8/redis:7.2.4-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$$REDIS_PASSWORD", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:
  redis_data:
